apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-api
  labels:
    app: cats-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-api
  template:
    metadata:
      labels:
        app: cats-api
    spec:
      containers:
      - name: cats-api
        image: devlifestartup/JOB_BASE_NAME:BUILD_NUMBER
        ports:
        - containerPort: 8088
        env:
          - name: DATASOURCE_HOST
            value: db.bromen.fun
          - name: DATASOURCE_PORT
            value: "5432"
          - name: SERVICE_NAME
            value: cats
          - name: SERVICE_PORT
            value: "8088"
---
apiVersion: v1
kind: Service
metadata:
  name: cats-api
spec:
  selector:
    app: cats-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088